name: mlproj
channels:
- defaults
dependencies:
- cairo=1.14.8=0
- cycler=0.10.0=py27_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.0=np112py27_0
- mkl=2017.0.1=0
- numpy=1.12.1=py27_0
- openssl=1.0.2k=1
- pandas=0.19.2=np112py27_1
- pcre=8.39=1
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- pycairo=1.10.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=3
- readline=6.2=2
- requests=2.13.0=py27_0
- scikit-learn=0.18.1=np112py27_1
- scipy=0.19.0=np112py27_0
- setuptools=27.2.0=py27_0
- simplejson=3.10.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- tk=8.5.18=0
- tqdm=4.11.2=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - geopy==1.11.0
  - httpie==0.9.9
  - pygments==2.2.0
prefix: /home/aju/miniconda3/envs/mlproj

